# @package __global__

defaults:
  - compression/default
  - /model: encodec/encodec_large_nq4_s640
  - override /dset: audio/default
  - _self_

channels: 1
sample_rate: 32000

losses:
  adv: 4.
  feat: 4.
  l1: 0.1
  mel: 0.
  msspec: 2.
  sisnr: 0.
  mmd: 1000.

mmd: 
  num_batches_mmd: 32
  delay: True